apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-sealyun-lvscare
  namespace: kube-system
spec:
  containers:
    - args:
        - care
        - --vs
        - 10.103.97.2:6443
        - --health-path
        - /healthz
        - --health-schem
        - https
        - --rs
        - 172.16.7.31:6443
        - --logger
        - DEBG
      command:
        - /usr/bin/lvscare-test
      image: ghcr.io/labring/lvscare:v1.1.3-beta.4
      imagePullPolicy: IfNotPresent
      name: kube-sealyun-lvscare
      resources: {}
      env:
        - name: NODE_IP
          value: 172.16.81.61
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /root/.kube/config
          name: kubeconfig
          readOnly: true
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /usr/bin/lvscare-test
          name: lvscare
          readOnly: false
  hostNetwork: true
  volumes:
    - hostPath:
        path: /etc/kubernetes/kubelet.conf
        type: ""
      name: kubeconfig
    - hostPath:
        path: /lib/modules
        type: ""
      name: lib-modules
    - hostPath:
        path: /root/lvscare
        type: ""
      name: lvscare
